#!/usr/bin/env python3
"""
Generates sw-filelist.js containing the list of all files the service worker
should precache for offline use. Run after adding/changing any assets.

Usage: python3 generate-sw-filelist.py
"""

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent

PRECACHE_PATTERNS = {
    "app_shell": [
        "index.html",
        "style.css",
        "app.js",
        "manifest.json",
        "gpx-manifest.json",
        "pics-manifest.json",
        "icons/icon-192x192.png",
        "icons/icon-512x512.png",
        "icons/icon.svg",
    ],
    "cdn": [
        "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css",
        "https://unpkg.com/leaflet@1.9.4/dist/leaflet.js",
        "https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js",
    ],
}

SCAN_DIRS = ["gpx", "pics/thumbs", "pics/web"]
EXTENSIONS = {".gpx", ".jpg", ".jpeg", ".png"}


def scan_files():
    files = []
    for scan_dir in SCAN_DIRS:
        dirpath = ROOT / scan_dir
        if not dirpath.exists():
            continue
        for fp in sorted(dirpath.rglob("*")):
            if fp.is_file() and fp.suffix.lower() in EXTENSIONS:
                files.append(str(fp.relative_to(ROOT)))
    return files


def main():
    asset_files = scan_files()
    all_local = PRECACHE_PATTERNS["app_shell"] + asset_files
    all_cdn = PRECACHE_PATTERNS["cdn"]

    output = (
        f"// Auto-generated by generate-sw-filelist.py — do not edit\n"
        f"const PRECACHE_LOCAL = {json.dumps(all_local, indent=2)};\n\n"
        f"const PRECACHE_CDN = {json.dumps(all_cdn, indent=2)};\n"
    )

    outpath = ROOT / "sw-filelist.js"
    outpath.write_text(output)

    print(f"Written {len(all_local)} local + {len(all_cdn)} CDN = {len(all_local) + len(all_cdn)} entries to sw-filelist.js")
    print(f"  App shell: {len(PRECACHE_PATTERNS['app_shell'])}")
    print(f"  GPX files: {sum(1 for f in asset_files if f.endswith('.gpx'))}")
    print(f"  Thumbnails: {sum(1 for f in asset_files if 'thumbs' in f)}")
    print(f"  Web images: {sum(1 for f in asset_files if 'pics/web' in f)}")
    print(f"  CDN libs: {len(all_cdn)}")


if __name__ == "__main__":
    main()
